name: Enforce License Compliance

on:
  pull_request:

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@d0aa91b82375e45135e96c02f17ce3b8002867cd # main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
