name: jest balancer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'
jobs:
  jest-balance:
    # Buckle up, this may take a while
    timeout-minutes: 60
    # Make sure this matches the runner that runs frontend tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        name: Checkout sentry

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        id: setup-node
        with:
          node-version-file: '.node-version'

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: node_modules cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: nodemodulescache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml', 'api-docs/pnpm-lock.yaml', '.node-version') }}

      - name: Install Javascript Dependencies
        if: steps.nodemodulescache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: jest balancer
        env:
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          GITHUB_PR_REF: ${{ github.event.pull_request.head.ref || github.ref }}
        run: JEST_TEST_BALANCER=1 pnpm run test-ci

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: jest-balance.json
          path: tests/js/test-balancer/jest-balance.json
